### ISSUE TITLE
Specify location for -p option

### ISSUE THREAD

**Issue by EvilUnicorn1304** [bichenkk/coinmon#44]
The -p option works fine in Linux, but in Windows I cannot specify an alternate location when running Coinmon in PowerShell.

**Comment by vladei** [comment]
I will take a look :)

**Comment by edegrave** [comment]
Brilliant! I use coinmon at work to and have no other option then windows!

**Comment by vladei** [comment]
I've just created a pull request in order to set a customizable path for your portfolio, instead of the Linux hardcored one. I've contacted @bichenkk and he will merge the pull request asap 😃  
After that please let me know if that fixed your issue because unfortunately I'm not a Windows user and I don't own any Windows machines atm 😞

**Comment by bichenkk** [comment]
Hey @edegrave @EvilUnicorn1304 Please update!
@vladei has made this available and I have added it into 0.0.17!

Thanks @vladei !

**Comment by EvilUnicorn1304** [comment]
Hi guys:

I just tested: coinmon -p D:\coinmon\portfolio\portfolio.json -c eur

Unfortunately I'm getting: Please include a valid json file. The file used is the same as the one used on Linux.

**Comment by vladei** [comment]
@EvilUnicorn1304 can you please provide me with your JSON config and I will try to find a windows machine to test it on my own.

**Comment by EvilUnicorn1304** [comment]
Sure: I've used this one to test:

{
"dent": 1770561,
"trx": 4521,
"dbc": 7078.48091376,
"dash": 1.995,
"kcs": 27.71,
"cmp": 276
}
