### ISSUE TITLE
Default currency

### ISSUE THREAD

**Issue by TomaszWaszczyk** [bichenkk/coinmon#60]
There is no default currency:

```
twaszczyk@kattomwasnb:~/workspaces/silesia-blockchain-meetup$ coinmon -c eth
We cannot convert to your currency.
twaszczyk@kattomwasnb:~/workspaces/silesia-blockchain-meetup$ coinmon -c usd
```
Cool to setup default currency like USD.

Thanks for the project!

**Comment by gzog** [comment]
@TomaszWaszczyk Not entirely sure what you mean since the default currency is USD. The second parameter is the default parameter according to [commander docs](https://github.com/tj/commander.js/#default-option-value).
https://github.com/bichenkk/coinmon/blob/3ca05ca1b0bf4aa4a1c906bb098049e70e2b6271/src/index.js#L21

It looks like ETH is currently not supported afaik. Making that fix now.
